providers:
  docker:
    exposedByDefault: false
    defaultRule: Host(`{{ normalize .Name }}.beannet.app`)
  file:
    filename: /etc/traefik/dynamic.yml

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    asDefault: true
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    asDefault: true
    address: :443
    http:
      tls:
        certResolver: cloudflare
      middlewares:
        - auth@docker
  auth:
    address: :8443
    http:
      tls:
        certResolver: cloudflare

certificatesResolvers:
  cloudflare:
    acme:
      email: elliott.chalford@gmail.com
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging

experimental:
  plugins:
    themepark:
      modulename: github.com/packruler/traefik-themepark
      version: v1.2.0
