name: Deploy

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: x86_64-linux

    outputs:
      hosts: ${{ steps.get_hosts.outputs.hosts }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Hosts
        id: get_hosts
        run: echo "hosts=$(nix eval --json --apply builtins.attrNames .#deploy.nodes )" >> "$GITHUB_OUTPUT"

      - name: Checks...
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: x86_64-linux
    environment: ${{ matrix.host }}

    needs: setup
    strategy:
      matrix:
        host: ${{ fromJSON(needs.setup.outputs.hosts) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Activate Shell
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#deploy

      - name: Build & Deploy
        env:
          SSHOPTS: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /run/agenix/key-deploy
        run: deploy -s --ssh-opts "$SSHOPTS" .#${{ matrix.host }}
