name: Diff

# TODO
# Implement home-manager diff using
#   https://discourse.nixos.org/t/viewing-differences-between-flake-revisions/18768/2

on: [deployment_status]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    outputs:
      old_deployment: ${{ steps.deployments.outputs.sha }}
      new_deployment: ${{ github.sha }}

    steps:
      - name: Get Previous Deployment
        id: deployments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deployments="$(gh api repos/${{ github.repository }}/deployments | jq -r '[.[] | select(.environment == "${{ github.event.deployment_status.environment }}")] | sort_by(.created_at) | reverse')"

          sha=""
          for deployment in $(echo "$deployments" | jq -r '.[].id'); do
            statuses="$(gh api "repos/${{ github.repository }}/deployments/${deployment}/statuses")"
            if echo "$statuses" | jq -e '.[] | select(.state == "inactive")' > /dev/null; then
              sha="$(echo "$deployments" | jq -r --arg id "$deployment" '.[] | select(.id == ($id | tonumber)) | .sha')"
              break
            fi
          done
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

  diff:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.old_deployment != '' }}

    env:
      host: ${{ github.event.deployment_status.environment }}

    steps:
      - name: Setup Nix
        uses: ElliottSullingeFarrall/dotfiles/.github/actions/setup@main

      - name: Build NixOS
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: |
            nix build --out-link old github:${{ github.repository}}/${{ needs.check.outputs.old_deployment }}#nixosConfigurations.${{ env.host }}.config.system.build.toplevel
            nix build --out-link new github:${{ github.repository}}/${{ needs.check.outputs.new_deployment }}#nixosConfigurations.${{ env.host }}.config.system.build.toplevel

      - name: Diff NixOS
        run: |
          mkdir -p changes
          nix run gitlab:khumba/nvd --no-write-lock-file -- diff old new > changes/${{ env.host }}.diff

      - name: Upload Diff
        uses: actions/upload-artifact@v4
        with:
          name: changes
          path: changes
